# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
# images used by GenAIExamples: knowledge_graphs
services:
  knowledge_graphs:
    build:
      dockerfile: comps/knowledgegraphs/langchain/docker/Dockerfile
    image: ${REGISTRY}opea/knowledge_graphs:${TAG:-latest}
