# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Comps CD workflow on manual event
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      services: "dataprep" #${{ steps.get-matrix.outputs.services }}
      names: "_pgvector" #${{ steps.get-matrix.outputs.names }}

  run-services:
    needs: [get-test-matrix]
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-test-matrix.outputs.services) }}
        # node: ${{ fromJson(needs.get-test-matrix.outputs.nodes) }}
        name: ${{ fromJson(needs.get-test-matrix.outputs.names }}
      fail-fast: false
    # uses: ./.github/workflows/_comps-workflow.yml
    with:
      service: ${{ matrix.service }}
      name: ${{ matrix.name }}
      tag: "comps" #${{ inputs.tag }}
    steps: |
      echo $service, $name, $tag

      # build: ${{ fromJSON(inputs.build) }}
      # scan: ${{ fromJSON(inputs.scan) }}
      # test_compose: ${{ fromJSON(inputs.test_compose) }}

      # GenAIComps_branch: ${{ inputs.GenAIComps_branch }}
    secrets: inherit
